// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_account_id", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "picture", Type: field.TypeString, Default: ""},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "bio", Type: field.TypeString, Default: ""},
		{Name: "registered_at", Type: field.TypeTime, Nullable: true},
		{Name: "webauthn_user_handle", Type: field.TypeBytes, Unique: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "account_provider_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[3], AccountsColumns[4]},
			},
			{
				Name:    "account_email",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[5]},
			},
		},
	}
	// WebauthnCredentialsColumns holds the columns for the "webauthn_credentials" table.
	WebauthnCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeInt64},
		{Name: "credential_id", Type: field.TypeBytes, Unique: true},
		{Name: "credential_json", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
	}
	// WebauthnCredentialsTable holds the schema information for the "webauthn_credentials" table.
	WebauthnCredentialsTable = &schema.Table{
		Name:       "webauthn_credentials",
		Columns:    WebauthnCredentialsColumns,
		PrimaryKey: []*schema.Column{WebauthnCredentialsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webauthncredential_account_id",
				Unique:  false,
				Columns: []*schema.Column{WebauthnCredentialsColumns[1]},
			},
		},
	}
	// WebauthnSessionsColumns holds the columns for the "webauthn_sessions" table.
	WebauthnSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "account_id", Type: field.TypeInt64, Nullable: true},
		{Name: "ceremony", Type: field.TypeString},
		{Name: "session_json", Type: field.TypeJSON},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WebauthnSessionsTable holds the schema information for the "webauthn_sessions" table.
	WebauthnSessionsTable = &schema.Table{
		Name:       "webauthn_sessions",
		Columns:    WebauthnSessionsColumns,
		PrimaryKey: []*schema.Column{WebauthnSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webauthnsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{WebauthnSessionsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		WebauthnCredentialsTable,
		WebauthnSessionsTable,
	}
)

func init() {
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	WebauthnCredentialsTable.Annotation = &entsql.Annotation{
		Table: "webauthn_credentials",
	}
	WebauthnSessionsTable.Annotation = &entsql.Annotation{
		Table: "webauthn_sessions",
	}
}
