// Code generated by ent, DO NOT EDIT.

package oidcclientredirecturi

import (
	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-auth/src/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldClientID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldRedirectURI, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldContainsFold(FieldClientID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.FieldContainsFold(FieldRedirectURI, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCClientRedirectURI) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCClientRedirectURI) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCClientRedirectURI) predicate.OIDCClientRedirectURI {
	return predicate.OIDCClientRedirectURI(sql.NotPredicates(p))
}
