// Code generated by ent, DO NOT EDIT.

package oidcclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldClientID, v))
}

// ClientSecretHash applies equality check predicate on the "client_secret_hash" field. It's identical to ClientSecretHashEQ.
func ClientSecretHash(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldDisabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretHashEQ applies the EQ predicate on the "client_secret_hash" field.
func ClientSecretHashEQ(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientSecretHashNEQ applies the NEQ predicate on the "client_secret_hash" field.
func ClientSecretHashNEQ(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldClientSecretHash, v))
}

// ClientSecretHashIn applies the In predicate on the "client_secret_hash" field.
func ClientSecretHashIn(vs ...[]byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashNotIn applies the NotIn predicate on the "client_secret_hash" field.
func ClientSecretHashNotIn(vs ...[]byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNotIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashGT applies the GT predicate on the "client_secret_hash" field.
func ClientSecretHashGT(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGT(FieldClientSecretHash, v))
}

// ClientSecretHashGTE applies the GTE predicate on the "client_secret_hash" field.
func ClientSecretHashGTE(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldGTE(FieldClientSecretHash, v))
}

// ClientSecretHashLT applies the LT predicate on the "client_secret_hash" field.
func ClientSecretHashLT(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLT(FieldClientSecretHash, v))
}

// ClientSecretHashLTE applies the LTE predicate on the "client_secret_hash" field.
func ClientSecretHashLTE(v []byte) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldLTE(FieldClientSecretHash, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.OIDCClient {
	return predicate.OIDCClient(sql.FieldNEQ(FieldDisabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCClient) predicate.OIDCClient {
	return predicate.OIDCClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCClient) predicate.OIDCClient {
	return predicate.OIDCClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCClient) predicate.OIDCClient {
	return predicate.OIDCClient(sql.NotPredicates(p))
}
