// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sandbox-nextjs/api/src/ent/account"
	"sandbox-nextjs/api/src/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpdate) SetProvider(v string) *AccountUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableProvider(v *string) *AccountUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderAccountID sets the "provider_account_id" field.
func (_u *AccountUpdate) SetProviderAccountID(v string) *AccountUpdate {
	_u.mutation.SetProviderAccountID(v)
	return _u
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableProviderAccountID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetProviderAccountID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AccountUpdate) SetEmail(v string) *AccountUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableEmail(v *string) *AccountUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *AccountUpdate) SetEmailVerified(v bool) *AccountUpdate {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableEmailVerified(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *AccountUpdate) SetPicture(v string) *AccountUpdate {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *AccountUpdate) SetNillablePicture(v *string) *AccountUpdate {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AccountUpdate) SetDisplayName(v string) *AccountUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDisplayName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *AccountUpdate) SetBio(v string) *AccountUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBio(v *string) *AccountUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *AccountUpdate) SetRegisteredAt(v time.Time) *AccountUpdate {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableRegisteredAt(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// ClearRegisteredAt clears the value of the "registered_at" field.
func (_u *AccountUpdate) ClearRegisteredAt() *AccountUpdate {
	_u.mutation.ClearRegisteredAt()
	return _u
}

// SetWebauthnUserHandle sets the "webauthn_user_handle" field.
func (_u *AccountUpdate) SetWebauthnUserHandle(v []byte) *AccountUpdate {
	_u.mutation.SetWebauthnUserHandle(v)
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(account.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountID(); ok {
		_spec.SetField(account.FieldProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(account.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(account.FieldPicture, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(account.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(account.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(account.FieldRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.RegisteredAtCleared() {
		_spec.ClearField(account.FieldRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WebauthnUserHandle(); ok {
		_spec.SetField(account.FieldWebauthnUserHandle, field.TypeBytes, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpdateOne) SetProvider(v string) *AccountUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableProvider(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderAccountID sets the "provider_account_id" field.
func (_u *AccountUpdateOne) SetProviderAccountID(v string) *AccountUpdateOne {
	_u.mutation.SetProviderAccountID(v)
	return _u
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableProviderAccountID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetProviderAccountID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AccountUpdateOne) SetEmail(v string) *AccountUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableEmail(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *AccountUpdateOne) SetEmailVerified(v bool) *AccountUpdateOne {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableEmailVerified(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *AccountUpdateOne) SetPicture(v string) *AccountUpdateOne {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillablePicture(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AccountUpdateOne) SetDisplayName(v string) *AccountUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDisplayName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *AccountUpdateOne) SetBio(v string) *AccountUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBio(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *AccountUpdateOne) SetRegisteredAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableRegisteredAt(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// ClearRegisteredAt clears the value of the "registered_at" field.
func (_u *AccountUpdateOne) ClearRegisteredAt() *AccountUpdateOne {
	_u.mutation.ClearRegisteredAt()
	return _u
}

// SetWebauthnUserHandle sets the "webauthn_user_handle" field.
func (_u *AccountUpdateOne) SetWebauthnUserHandle(v []byte) *AccountUpdateOne {
	_u.mutation.SetWebauthnUserHandle(v)
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(account.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountID(); ok {
		_spec.SetField(account.FieldProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(account.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(account.FieldPicture, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(account.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(account.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(account.FieldRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.RegisteredAtCleared() {
		_spec.ClearField(account.FieldRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WebauthnUserHandle(); ok {
		_spec.SetField(account.FieldWebauthnUserHandle, field.TypeBytes, value)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
