// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/authsession"
)

// AuthSessionCreate is the builder for creating a AuthSession entity.
type AuthSessionCreate struct {
	config
	mutation *AuthSessionMutation
	hooks    []Hook
}

// SetTokenHash sets the "token_hash" field.
func (_c *AuthSessionCreate) SetTokenHash(v []byte) *AuthSessionCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AuthSessionCreate) SetAccountID(v int64) *AuthSessionCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthSessionCreate) SetExpiresAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AuthSessionCreate) SetRevokedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableRevokedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthSessionCreate) SetCreatedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableCreatedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_c *AuthSessionCreate) Mutation() *AuthSessionMutation {
	return _c.mutation
}

// Save creates the AuthSession in the database.
func (_c *AuthSessionCreate) Save(ctx context.Context) (*AuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSessionCreate) SaveX(ctx context.Context) *AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSessionCreate) check() error {
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "AuthSession.token_hash"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AuthSession.account_id"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthSession.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthSession.created_at"`)}
	}
	return nil
}

func (_c *AuthSessionCreate) sqlSave(ctx context.Context) (*AuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSessionCreate) createSpec() (*AuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsession.Table, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(authsession.FieldTokenHash, field.TypeBytes, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(authsession.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(authsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuthSessionCreateBulk is the builder for creating many AuthSession entities in bulk.
type AuthSessionCreateBulk struct {
	config
	err      error
	builders []*AuthSessionCreate
}

// Save creates the AuthSession entities in the database.
func (_c *AuthSessionCreateBulk) Save(ctx context.Context) ([]*AuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) SaveX(ctx context.Context) []*AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
