// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"sandbox-nextjs/api/src/ent/migrate"

	"sandbox-nextjs/api/src/ent/account"
	"sandbox-nextjs/api/src/ent/webauthncredential"
	"sandbox-nextjs/api/src/ent/webauthnsession"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Account is the client for interacting with the Account builders.
	Account *AccountClient
	// WebauthnCredential is the client for interacting with the WebauthnCredential builders.
	WebauthnCredential *WebauthnCredentialClient
	// WebauthnSession is the client for interacting with the WebauthnSession builders.
	WebauthnSession *WebauthnSessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Account = NewAccountClient(c.config)
	c.WebauthnCredential = NewWebauthnCredentialClient(c.config)
	c.WebauthnSession = NewWebauthnSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Account:            NewAccountClient(cfg),
		WebauthnCredential: NewWebauthnCredentialClient(cfg),
		WebauthnSession:    NewWebauthnSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Account:            NewAccountClient(cfg),
		WebauthnCredential: NewWebauthnCredentialClient(cfg),
		WebauthnSession:    NewWebauthnSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Account.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Account.Use(hooks...)
	c.WebauthnCredential.Use(hooks...)
	c.WebauthnSession.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Account.Intercept(interceptors...)
	c.WebauthnCredential.Intercept(interceptors...)
	c.WebauthnSession.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AccountMutation:
		return c.Account.mutate(ctx, m)
	case *WebauthnCredentialMutation:
		return c.WebauthnCredential.mutate(ctx, m)
	case *WebauthnSessionMutation:
		return c.WebauthnSession.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AccountClient is a client for the Account schema.
type AccountClient struct {
	config
}

// NewAccountClient returns a client for the Account from the given config.
func NewAccountClient(c config) *AccountClient {
	return &AccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `account.Hooks(f(g(h())))`.
func (c *AccountClient) Use(hooks ...Hook) {
	c.hooks.Account = append(c.hooks.Account, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `account.Intercept(f(g(h())))`.
func (c *AccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.Account = append(c.inters.Account, interceptors...)
}

// Create returns a builder for creating a Account entity.
func (c *AccountClient) Create() *AccountCreate {
	mutation := newAccountMutation(c.config, OpCreate)
	return &AccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Account entities.
func (c *AccountClient) CreateBulk(builders ...*AccountCreate) *AccountCreateBulk {
	return &AccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AccountClient) MapCreateBulk(slice any, setFunc func(*AccountCreate, int)) *AccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AccountCreateBulk{err: fmt.Errorf("calling to AccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Account.
func (c *AccountClient) Update() *AccountUpdate {
	mutation := newAccountMutation(c.config, OpUpdate)
	return &AccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountClient) UpdateOne(_m *Account) *AccountUpdateOne {
	mutation := newAccountMutation(c.config, OpUpdateOne, withAccount(_m))
	return &AccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountClient) UpdateOneID(id int) *AccountUpdateOne {
	mutation := newAccountMutation(c.config, OpUpdateOne, withAccountID(id))
	return &AccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Account.
func (c *AccountClient) Delete() *AccountDelete {
	mutation := newAccountMutation(c.config, OpDelete)
	return &AccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AccountClient) DeleteOne(_m *Account) *AccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AccountClient) DeleteOneID(id int) *AccountDeleteOne {
	builder := c.Delete().Where(account.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountDeleteOne{builder}
}

// Query returns a query builder for Account.
func (c *AccountClient) Query() *AccountQuery {
	return &AccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a Account entity by its id.
func (c *AccountClient) Get(ctx context.Context, id int) (*Account, error) {
	return c.Query().Where(account.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountClient) GetX(ctx context.Context, id int) *Account {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AccountClient) Hooks() []Hook {
	return c.hooks.Account
}

// Interceptors returns the client interceptors.
func (c *AccountClient) Interceptors() []Interceptor {
	return c.inters.Account
}

func (c *AccountClient) mutate(ctx context.Context, m *AccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Account mutation op: %q", m.Op())
	}
}

// WebauthnCredentialClient is a client for the WebauthnCredential schema.
type WebauthnCredentialClient struct {
	config
}

// NewWebauthnCredentialClient returns a client for the WebauthnCredential from the given config.
func NewWebauthnCredentialClient(c config) *WebauthnCredentialClient {
	return &WebauthnCredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `webauthncredential.Hooks(f(g(h())))`.
func (c *WebauthnCredentialClient) Use(hooks ...Hook) {
	c.hooks.WebauthnCredential = append(c.hooks.WebauthnCredential, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `webauthncredential.Intercept(f(g(h())))`.
func (c *WebauthnCredentialClient) Intercept(interceptors ...Interceptor) {
	c.inters.WebauthnCredential = append(c.inters.WebauthnCredential, interceptors...)
}

// Create returns a builder for creating a WebauthnCredential entity.
func (c *WebauthnCredentialClient) Create() *WebauthnCredentialCreate {
	mutation := newWebauthnCredentialMutation(c.config, OpCreate)
	return &WebauthnCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WebauthnCredential entities.
func (c *WebauthnCredentialClient) CreateBulk(builders ...*WebauthnCredentialCreate) *WebauthnCredentialCreateBulk {
	return &WebauthnCredentialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WebauthnCredentialClient) MapCreateBulk(slice any, setFunc func(*WebauthnCredentialCreate, int)) *WebauthnCredentialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WebauthnCredentialCreateBulk{err: fmt.Errorf("calling to WebauthnCredentialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WebauthnCredentialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WebauthnCredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WebauthnCredential.
func (c *WebauthnCredentialClient) Update() *WebauthnCredentialUpdate {
	mutation := newWebauthnCredentialMutation(c.config, OpUpdate)
	return &WebauthnCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WebauthnCredentialClient) UpdateOne(_m *WebauthnCredential) *WebauthnCredentialUpdateOne {
	mutation := newWebauthnCredentialMutation(c.config, OpUpdateOne, withWebauthnCredential(_m))
	return &WebauthnCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WebauthnCredentialClient) UpdateOneID(id int) *WebauthnCredentialUpdateOne {
	mutation := newWebauthnCredentialMutation(c.config, OpUpdateOne, withWebauthnCredentialID(id))
	return &WebauthnCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WebauthnCredential.
func (c *WebauthnCredentialClient) Delete() *WebauthnCredentialDelete {
	mutation := newWebauthnCredentialMutation(c.config, OpDelete)
	return &WebauthnCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WebauthnCredentialClient) DeleteOne(_m *WebauthnCredential) *WebauthnCredentialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WebauthnCredentialClient) DeleteOneID(id int) *WebauthnCredentialDeleteOne {
	builder := c.Delete().Where(webauthncredential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WebauthnCredentialDeleteOne{builder}
}

// Query returns a query builder for WebauthnCredential.
func (c *WebauthnCredentialClient) Query() *WebauthnCredentialQuery {
	return &WebauthnCredentialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWebauthnCredential},
		inters: c.Interceptors(),
	}
}

// Get returns a WebauthnCredential entity by its id.
func (c *WebauthnCredentialClient) Get(ctx context.Context, id int) (*WebauthnCredential, error) {
	return c.Query().Where(webauthncredential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WebauthnCredentialClient) GetX(ctx context.Context, id int) *WebauthnCredential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WebauthnCredentialClient) Hooks() []Hook {
	return c.hooks.WebauthnCredential
}

// Interceptors returns the client interceptors.
func (c *WebauthnCredentialClient) Interceptors() []Interceptor {
	return c.inters.WebauthnCredential
}

func (c *WebauthnCredentialClient) mutate(ctx context.Context, m *WebauthnCredentialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WebauthnCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WebauthnCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WebauthnCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WebauthnCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WebauthnCredential mutation op: %q", m.Op())
	}
}

// WebauthnSessionClient is a client for the WebauthnSession schema.
type WebauthnSessionClient struct {
	config
}

// NewWebauthnSessionClient returns a client for the WebauthnSession from the given config.
func NewWebauthnSessionClient(c config) *WebauthnSessionClient {
	return &WebauthnSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `webauthnsession.Hooks(f(g(h())))`.
func (c *WebauthnSessionClient) Use(hooks ...Hook) {
	c.hooks.WebauthnSession = append(c.hooks.WebauthnSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `webauthnsession.Intercept(f(g(h())))`.
func (c *WebauthnSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.WebauthnSession = append(c.inters.WebauthnSession, interceptors...)
}

// Create returns a builder for creating a WebauthnSession entity.
func (c *WebauthnSessionClient) Create() *WebauthnSessionCreate {
	mutation := newWebauthnSessionMutation(c.config, OpCreate)
	return &WebauthnSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WebauthnSession entities.
func (c *WebauthnSessionClient) CreateBulk(builders ...*WebauthnSessionCreate) *WebauthnSessionCreateBulk {
	return &WebauthnSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WebauthnSessionClient) MapCreateBulk(slice any, setFunc func(*WebauthnSessionCreate, int)) *WebauthnSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WebauthnSessionCreateBulk{err: fmt.Errorf("calling to WebauthnSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WebauthnSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WebauthnSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WebauthnSession.
func (c *WebauthnSessionClient) Update() *WebauthnSessionUpdate {
	mutation := newWebauthnSessionMutation(c.config, OpUpdate)
	return &WebauthnSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WebauthnSessionClient) UpdateOne(_m *WebauthnSession) *WebauthnSessionUpdateOne {
	mutation := newWebauthnSessionMutation(c.config, OpUpdateOne, withWebauthnSession(_m))
	return &WebauthnSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WebauthnSessionClient) UpdateOneID(id string) *WebauthnSessionUpdateOne {
	mutation := newWebauthnSessionMutation(c.config, OpUpdateOne, withWebauthnSessionID(id))
	return &WebauthnSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WebauthnSession.
func (c *WebauthnSessionClient) Delete() *WebauthnSessionDelete {
	mutation := newWebauthnSessionMutation(c.config, OpDelete)
	return &WebauthnSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WebauthnSessionClient) DeleteOne(_m *WebauthnSession) *WebauthnSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WebauthnSessionClient) DeleteOneID(id string) *WebauthnSessionDeleteOne {
	builder := c.Delete().Where(webauthnsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WebauthnSessionDeleteOne{builder}
}

// Query returns a query builder for WebauthnSession.
func (c *WebauthnSessionClient) Query() *WebauthnSessionQuery {
	return &WebauthnSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWebauthnSession},
		inters: c.Interceptors(),
	}
}

// Get returns a WebauthnSession entity by its id.
func (c *WebauthnSessionClient) Get(ctx context.Context, id string) (*WebauthnSession, error) {
	return c.Query().Where(webauthnsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WebauthnSessionClient) GetX(ctx context.Context, id string) *WebauthnSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WebauthnSessionClient) Hooks() []Hook {
	return c.hooks.WebauthnSession
}

// Interceptors returns the client interceptors.
func (c *WebauthnSessionClient) Interceptors() []Interceptor {
	return c.inters.WebauthnSession
}

func (c *WebauthnSessionClient) mutate(ctx context.Context, m *WebauthnSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WebauthnSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WebauthnSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WebauthnSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WebauthnSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WebauthnSession mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Account, WebauthnCredential, WebauthnSession []ent.Hook
	}
	inters struct {
		Account, WebauthnCredential, WebauthnSession []ent.Interceptor
	}
)
