// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcauthorizationtransaction"
)

// OIDCAuthorizationTransactionCreate is the builder for creating a OIDCAuthorizationTransaction entity.
type OIDCAuthorizationTransactionCreate struct {
	config
	mutation *OIDCAuthorizationTransactionMutation
	hooks    []Hook
}

// SetTransactionHash sets the "transaction_hash" field.
func (_c *OIDCAuthorizationTransactionCreate) SetTransactionHash(v []byte) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetTransactionHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OIDCAuthorizationTransactionCreate) SetClientID(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OIDCAuthorizationTransactionCreate) SetRedirectURI(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *OIDCAuthorizationTransactionCreate) SetScope(v []string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OIDCAuthorizationTransactionCreate) SetState(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OIDCAuthorizationTransactionCreate) SetNillableState(v *string) *OIDCAuthorizationTransactionCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *OIDCAuthorizationTransactionCreate) SetNonce(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OIDCAuthorizationTransactionCreate) SetCodeChallenge(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OIDCAuthorizationTransactionCreate) SetCodeChallengeMethod(v string) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OIDCAuthorizationTransactionCreate) SetExpiresAt(v time.Time) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OIDCAuthorizationTransactionCreate) SetConsumedAt(v time.Time) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OIDCAuthorizationTransactionCreate) SetNillableConsumedAt(v *time.Time) *OIDCAuthorizationTransactionCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCAuthorizationTransactionCreate) SetCreatedAt(v time.Time) *OIDCAuthorizationTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCAuthorizationTransactionCreate) SetNillableCreatedAt(v *time.Time) *OIDCAuthorizationTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the OIDCAuthorizationTransactionMutation object of the builder.
func (_c *OIDCAuthorizationTransactionCreate) Mutation() *OIDCAuthorizationTransactionMutation {
	return _c.mutation
}

// Save creates the OIDCAuthorizationTransaction in the database.
func (_c *OIDCAuthorizationTransactionCreate) Save(ctx context.Context) (*OIDCAuthorizationTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCAuthorizationTransactionCreate) SaveX(ctx context.Context) *OIDCAuthorizationTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCAuthorizationTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCAuthorizationTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCAuthorizationTransactionCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := oidcauthorizationtransaction.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oidcauthorizationtransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCAuthorizationTransactionCreate) check() error {
	if _, ok := _c.mutation.TransactionHash(); !ok {
		return &ValidationError{Name: "transaction_hash", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.transaction_hash"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.client_id"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.redirect_uri"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.scope"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.state"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.nonce"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.code_challenge"`)}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.code_challenge_method"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OIDCAuthorizationTransaction.created_at"`)}
	}
	return nil
}

func (_c *OIDCAuthorizationTransactionCreate) sqlSave(ctx context.Context) (*OIDCAuthorizationTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCAuthorizationTransactionCreate) createSpec() (*OIDCAuthorizationTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCAuthorizationTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcauthorizationtransaction.Table, sqlgraph.NewFieldSpec(oidcauthorizationtransaction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TransactionHash(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldTransactionHash, field.TypeBytes, value)
		_node.TransactionHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldScope, field.TypeJSON, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcauthorizationtransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OIDCAuthorizationTransactionCreateBulk is the builder for creating many OIDCAuthorizationTransaction entities in bulk.
type OIDCAuthorizationTransactionCreateBulk struct {
	config
	err      error
	builders []*OIDCAuthorizationTransactionCreate
}

// Save creates the OIDCAuthorizationTransaction entities in the database.
func (_c *OIDCAuthorizationTransactionCreateBulk) Save(ctx context.Context) ([]*OIDCAuthorizationTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCAuthorizationTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCAuthorizationTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCAuthorizationTransactionCreateBulk) SaveX(ctx context.Context) []*OIDCAuthorizationTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCAuthorizationTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCAuthorizationTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
