// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/oidcauthorizationcode"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// OIDCAuthorizationCodeUpdate is the builder for updating OIDCAuthorizationCode entities.
type OIDCAuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *OIDCAuthorizationCodeMutation
}

// Where appends a list predicates to the OIDCAuthorizationCodeUpdate builder.
func (_u *OIDCAuthorizationCodeUpdate) Where(ps ...predicate.OIDCAuthorizationCode) *OIDCAuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *OIDCAuthorizationCodeUpdate) SetCodeHash(v []byte) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCAuthorizationCodeUpdate) SetClientID(v string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableClientID(v *string) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OIDCAuthorizationCodeUpdate) SetRedirectURI(v string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableRedirectURI(v *string) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OIDCAuthorizationCodeUpdate) SetAccountID(v int64) *OIDCAuthorizationCodeUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableAccountID(v *int64) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OIDCAuthorizationCodeUpdate) AddAccountID(v int64) *OIDCAuthorizationCodeUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *OIDCAuthorizationCodeUpdate) SetScope(v []string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// AppendScope appends value to the "scope" field.
func (_u *OIDCAuthorizationCodeUpdate) AppendScope(v []string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.AppendScope(v)
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *OIDCAuthorizationCodeUpdate) SetNonce(v string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableNonce(v *string) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OIDCAuthorizationCodeUpdate) SetCodeChallenge(v string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableCodeChallenge(v *string) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OIDCAuthorizationCodeUpdate) SetCodeChallengeMethod(v string) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableCodeChallengeMethod(v *string) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OIDCAuthorizationCodeUpdate) SetExpiresAt(v time.Time) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableExpiresAt(v *time.Time) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OIDCAuthorizationCodeUpdate) SetConsumedAt(v time.Time) *OIDCAuthorizationCodeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdate) SetNillableConsumedAt(v *time.Time) *OIDCAuthorizationCodeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OIDCAuthorizationCodeUpdate) ClearConsumedAt() *OIDCAuthorizationCodeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the OIDCAuthorizationCodeMutation object of the builder.
func (_u *OIDCAuthorizationCodeUpdate) Mutation() *OIDCAuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCAuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCAuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCAuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCAuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCAuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcauthorizationcode.Table, oidcauthorizationcode.Columns, sqlgraph.NewFieldSpec(oidcauthorizationcode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oidcauthorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(oidcauthorizationcode.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oidcauthorizationcode.FieldScope, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScope(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oidcauthorizationcode.FieldScope, value)
		})
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(oidcauthorizationcode.FieldNonce, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oidcauthorizationcode.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCAuthorizationCodeUpdateOne is the builder for updating a single OIDCAuthorizationCode entity.
type OIDCAuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OIDCAuthorizationCodeMutation
}

// SetCodeHash sets the "code_hash" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetCodeHash(v []byte) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetClientID(v string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableClientID(v *string) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetRedirectURI(v string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableRedirectURI(v *string) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetAccountID(v int64) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableAccountID(v *int64) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OIDCAuthorizationCodeUpdateOne) AddAccountID(v int64) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetScope(v []string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// AppendScope appends value to the "scope" field.
func (_u *OIDCAuthorizationCodeUpdateOne) AppendScope(v []string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.AppendScope(v)
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNonce(v string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableNonce(v *string) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetCodeChallenge(v string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableCodeChallenge(v *string) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetCodeChallengeMethod(v string) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableCodeChallengeMethod(v *string) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetExpiresAt(v time.Time) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OIDCAuthorizationCodeUpdateOne) SetConsumedAt(v time.Time) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OIDCAuthorizationCodeUpdateOne) SetNillableConsumedAt(v *time.Time) *OIDCAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OIDCAuthorizationCodeUpdateOne) ClearConsumedAt() *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the OIDCAuthorizationCodeMutation object of the builder.
func (_u *OIDCAuthorizationCodeUpdateOne) Mutation() *OIDCAuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCAuthorizationCodeUpdate builder.
func (_u *OIDCAuthorizationCodeUpdateOne) Where(ps ...predicate.OIDCAuthorizationCode) *OIDCAuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCAuthorizationCodeUpdateOne) Select(field string, fields ...string) *OIDCAuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCAuthorizationCode entity.
func (_u *OIDCAuthorizationCodeUpdateOne) Save(ctx context.Context) (*OIDCAuthorizationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCAuthorizationCodeUpdateOne) SaveX(ctx context.Context) *OIDCAuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCAuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCAuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCAuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *OIDCAuthorizationCode, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcauthorizationcode.Table, oidcauthorizationcode.Columns, sqlgraph.NewFieldSpec(oidcauthorizationcode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCAuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcauthorizationcode.FieldID)
		for _, f := range fields {
			if !oidcauthorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcauthorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oidcauthorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(oidcauthorizationcode.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oidcauthorizationcode.FieldScope, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScope(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oidcauthorizationcode.FieldScope, value)
		})
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(oidcauthorizationcode.FieldNonce, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oidcauthorizationcode.FieldConsumedAt, field.TypeTime)
	}
	_node = &OIDCAuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
