// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcclientredirecturi"
	"github.com/sandbox-auth/src/ent/predicate"
)

// OIDCClientRedirectURIUpdate is the builder for updating OIDCClientRedirectURI entities.
type OIDCClientRedirectURIUpdate struct {
	config
	hooks    []Hook
	mutation *OIDCClientRedirectURIMutation
}

// Where appends a list predicates to the OIDCClientRedirectURIUpdate builder.
func (_u *OIDCClientRedirectURIUpdate) Where(ps ...predicate.OIDCClientRedirectURI) *OIDCClientRedirectURIUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCClientRedirectURIUpdate) SetClientID(v string) *OIDCClientRedirectURIUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCClientRedirectURIUpdate) SetNillableClientID(v *string) *OIDCClientRedirectURIUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OIDCClientRedirectURIUpdate) SetRedirectURI(v string) *OIDCClientRedirectURIUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OIDCClientRedirectURIUpdate) SetNillableRedirectURI(v *string) *OIDCClientRedirectURIUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// Mutation returns the OIDCClientRedirectURIMutation object of the builder.
func (_u *OIDCClientRedirectURIUpdate) Mutation() *OIDCClientRedirectURIMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCClientRedirectURIUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCClientRedirectURIUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCClientRedirectURIUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCClientRedirectURIUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCClientRedirectURIUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcclientredirecturi.Table, oidcclientredirecturi.Columns, sqlgraph.NewFieldSpec(oidcclientredirecturi.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcclientredirecturi.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oidcclientredirecturi.FieldRedirectURI, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcclientredirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCClientRedirectURIUpdateOne is the builder for updating a single OIDCClientRedirectURI entity.
type OIDCClientRedirectURIUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OIDCClientRedirectURIMutation
}

// SetClientID sets the "client_id" field.
func (_u *OIDCClientRedirectURIUpdateOne) SetClientID(v string) *OIDCClientRedirectURIUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCClientRedirectURIUpdateOne) SetNillableClientID(v *string) *OIDCClientRedirectURIUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OIDCClientRedirectURIUpdateOne) SetRedirectURI(v string) *OIDCClientRedirectURIUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OIDCClientRedirectURIUpdateOne) SetNillableRedirectURI(v *string) *OIDCClientRedirectURIUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// Mutation returns the OIDCClientRedirectURIMutation object of the builder.
func (_u *OIDCClientRedirectURIUpdateOne) Mutation() *OIDCClientRedirectURIMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCClientRedirectURIUpdate builder.
func (_u *OIDCClientRedirectURIUpdateOne) Where(ps ...predicate.OIDCClientRedirectURI) *OIDCClientRedirectURIUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCClientRedirectURIUpdateOne) Select(field string, fields ...string) *OIDCClientRedirectURIUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCClientRedirectURI entity.
func (_u *OIDCClientRedirectURIUpdateOne) Save(ctx context.Context) (*OIDCClientRedirectURI, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCClientRedirectURIUpdateOne) SaveX(ctx context.Context) *OIDCClientRedirectURI {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCClientRedirectURIUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCClientRedirectURIUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCClientRedirectURIUpdateOne) sqlSave(ctx context.Context) (_node *OIDCClientRedirectURI, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcclientredirecturi.Table, oidcclientredirecturi.Columns, sqlgraph.NewFieldSpec(oidcclientredirecturi.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCClientRedirectURI.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcclientredirecturi.FieldID)
		for _, f := range fields {
			if !oidcclientredirecturi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcclientredirecturi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcclientredirecturi.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oidcclientredirecturi.FieldRedirectURI, field.TypeString, value)
	}
	_node = &OIDCClientRedirectURI{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcclientredirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
