// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcauthorizationtransaction"
	"github.com/sandbox-auth/src/ent/predicate"
)

// OIDCAuthorizationTransactionDelete is the builder for deleting a OIDCAuthorizationTransaction entity.
type OIDCAuthorizationTransactionDelete struct {
	config
	hooks    []Hook
	mutation *OIDCAuthorizationTransactionMutation
}

// Where appends a list predicates to the OIDCAuthorizationTransactionDelete builder.
func (_d *OIDCAuthorizationTransactionDelete) Where(ps ...predicate.OIDCAuthorizationTransaction) *OIDCAuthorizationTransactionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OIDCAuthorizationTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCAuthorizationTransactionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OIDCAuthorizationTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oidcauthorizationtransaction.Table, sqlgraph.NewFieldSpec(oidcauthorizationtransaction.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OIDCAuthorizationTransactionDeleteOne is the builder for deleting a single OIDCAuthorizationTransaction entity.
type OIDCAuthorizationTransactionDeleteOne struct {
	_d *OIDCAuthorizationTransactionDelete
}

// Where appends a list predicates to the OIDCAuthorizationTransactionDelete builder.
func (_d *OIDCAuthorizationTransactionDeleteOne) Where(ps ...predicate.OIDCAuthorizationTransaction) *OIDCAuthorizationTransactionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OIDCAuthorizationTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oidcauthorizationtransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCAuthorizationTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
