// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-nextjs/src/ent/oidcclient"
)

// OIDCClient is the model entity for the OIDCClient schema.
type OIDCClient struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// ClientSecretHash holds the value of the "client_secret_hash" field.
	ClientSecretHash []byte `json:"client_secret_hash,omitempty"`
	// Disabled holds the value of the "disabled" field.
	Disabled     bool `json:"disabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCClient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidcclient.FieldClientSecretHash:
			values[i] = new([]byte)
		case oidcclient.FieldDisabled:
			values[i] = new(sql.NullBool)
		case oidcclient.FieldID:
			values[i] = new(sql.NullInt64)
		case oidcclient.FieldClientID:
			values[i] = new(sql.NullString)
		case oidcclient.FieldCreatedAt, oidcclient.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCClient fields.
func (_m *OIDCClient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidcclient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oidcclient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oidcclient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oidcclient.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oidcclient.FieldClientSecretHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field client_secret_hash", values[i])
			} else if value != nil {
				_m.ClientSecretHash = *value
			}
		case oidcclient.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				_m.Disabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCClient.
// This includes values selected through modifiers, order, etc.
func (_m *OIDCClient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OIDCClient.
// Note that you need to call OIDCClient.Unwrap() before calling this method if this OIDCClient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OIDCClient) Update() *OIDCClientUpdateOne {
	return NewOIDCClientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OIDCClient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OIDCClient) Unwrap() *OIDCClient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCClient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OIDCClient) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCClient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("client_secret_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientSecretHash))
	builder.WriteString(", ")
	builder.WriteString("disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Disabled))
	builder.WriteByte(')')
	return builder.String()
}

// OIDCClients is a parsable slice of OIDCClient.
type OIDCClients []*OIDCClient
