// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/oidcclient"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// OIDCClientUpdate is the builder for updating OIDCClient entities.
type OIDCClientUpdate struct {
	config
	hooks    []Hook
	mutation *OIDCClientMutation
}

// Where appends a list predicates to the OIDCClientUpdate builder.
func (_u *OIDCClientUpdate) Where(ps ...predicate.OIDCClient) *OIDCClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCClientUpdate) SetUpdatedAt(v time.Time) *OIDCClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCClientUpdate) SetClientID(v string) *OIDCClientUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCClientUpdate) SetNillableClientID(v *string) *OIDCClientUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OIDCClientUpdate) SetClientSecretHash(v []byte) *OIDCClientUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *OIDCClientUpdate) SetDisabled(v bool) *OIDCClientUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *OIDCClientUpdate) SetNillableDisabled(v *bool) *OIDCClientUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// Mutation returns the OIDCClientMutation object of the builder.
func (_u *OIDCClientUpdate) Mutation() *OIDCClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oidcclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OIDCClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcclient.Table, oidcclient.Columns, sqlgraph.NewFieldSpec(oidcclient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oidcclient.FieldClientSecretHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(oidcclient.FieldDisabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCClientUpdateOne is the builder for updating a single OIDCClient entity.
type OIDCClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OIDCClientMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCClientUpdateOne) SetUpdatedAt(v time.Time) *OIDCClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCClientUpdateOne) SetClientID(v string) *OIDCClientUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCClientUpdateOne) SetNillableClientID(v *string) *OIDCClientUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OIDCClientUpdateOne) SetClientSecretHash(v []byte) *OIDCClientUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *OIDCClientUpdateOne) SetDisabled(v bool) *OIDCClientUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *OIDCClientUpdateOne) SetNillableDisabled(v *bool) *OIDCClientUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// Mutation returns the OIDCClientMutation object of the builder.
func (_u *OIDCClientUpdateOne) Mutation() *OIDCClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCClientUpdate builder.
func (_u *OIDCClientUpdateOne) Where(ps ...predicate.OIDCClient) *OIDCClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCClientUpdateOne) Select(field string, fields ...string) *OIDCClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCClient entity.
func (_u *OIDCClientUpdateOne) Save(ctx context.Context) (*OIDCClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCClientUpdateOne) SaveX(ctx context.Context) *OIDCClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oidcclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OIDCClientUpdateOne) sqlSave(ctx context.Context) (_node *OIDCClient, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcclient.Table, oidcclient.Columns, sqlgraph.NewFieldSpec(oidcclient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcclient.FieldID)
		for _, f := range fields {
			if !oidcclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oidcclient.FieldClientSecretHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(oidcclient.FieldDisabled, field.TypeBool, value)
	}
	_node = &OIDCClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
