// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/oidcclientredirecturi"
)

// OIDCClientRedirectURICreate is the builder for creating a OIDCClientRedirectURI entity.
type OIDCClientRedirectURICreate struct {
	config
	mutation *OIDCClientRedirectURIMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (_c *OIDCClientRedirectURICreate) SetClientID(v string) *OIDCClientRedirectURICreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OIDCClientRedirectURICreate) SetRedirectURI(v string) *OIDCClientRedirectURICreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// Mutation returns the OIDCClientRedirectURIMutation object of the builder.
func (_c *OIDCClientRedirectURICreate) Mutation() *OIDCClientRedirectURIMutation {
	return _c.mutation
}

// Save creates the OIDCClientRedirectURI in the database.
func (_c *OIDCClientRedirectURICreate) Save(ctx context.Context) (*OIDCClientRedirectURI, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCClientRedirectURICreate) SaveX(ctx context.Context) *OIDCClientRedirectURI {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCClientRedirectURICreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCClientRedirectURICreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCClientRedirectURICreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OIDCClientRedirectURI.client_id"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OIDCClientRedirectURI.redirect_uri"`)}
	}
	return nil
}

func (_c *OIDCClientRedirectURICreate) sqlSave(ctx context.Context) (*OIDCClientRedirectURI, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCClientRedirectURICreate) createSpec() (*OIDCClientRedirectURI, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCClientRedirectURI{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcclientredirecturi.Table, sqlgraph.NewFieldSpec(oidcclientredirecturi.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oidcclientredirecturi.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oidcclientredirecturi.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	return _node, _spec
}

// OIDCClientRedirectURICreateBulk is the builder for creating many OIDCClientRedirectURI entities in bulk.
type OIDCClientRedirectURICreateBulk struct {
	config
	err      error
	builders []*OIDCClientRedirectURICreate
}

// Save creates the OIDCClientRedirectURI entities in the database.
func (_c *OIDCClientRedirectURICreateBulk) Save(ctx context.Context) ([]*OIDCClientRedirectURI, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCClientRedirectURI, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCClientRedirectURIMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCClientRedirectURICreateBulk) SaveX(ctx context.Context) []*OIDCClientRedirectURI {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCClientRedirectURICreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCClientRedirectURICreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
