// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcauthorizationcode"
)

// OIDCAuthorizationCodeCreate is the builder for creating a OIDCAuthorizationCode entity.
type OIDCAuthorizationCodeCreate struct {
	config
	mutation *OIDCAuthorizationCodeMutation
	hooks    []Hook
}

// SetCodeHash sets the "code_hash" field.
func (_c *OIDCAuthorizationCodeCreate) SetCodeHash(v []byte) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OIDCAuthorizationCodeCreate) SetClientID(v string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OIDCAuthorizationCodeCreate) SetRedirectURI(v string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OIDCAuthorizationCodeCreate) SetAccountID(v int64) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *OIDCAuthorizationCodeCreate) SetScope(v []string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *OIDCAuthorizationCodeCreate) SetNonce(v string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OIDCAuthorizationCodeCreate) SetCodeChallenge(v string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OIDCAuthorizationCodeCreate) SetCodeChallengeMethod(v string) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OIDCAuthorizationCodeCreate) SetExpiresAt(v time.Time) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OIDCAuthorizationCodeCreate) SetConsumedAt(v time.Time) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OIDCAuthorizationCodeCreate) SetNillableConsumedAt(v *time.Time) *OIDCAuthorizationCodeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCAuthorizationCodeCreate) SetCreatedAt(v time.Time) *OIDCAuthorizationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCAuthorizationCodeCreate) SetNillableCreatedAt(v *time.Time) *OIDCAuthorizationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the OIDCAuthorizationCodeMutation object of the builder.
func (_c *OIDCAuthorizationCodeCreate) Mutation() *OIDCAuthorizationCodeMutation {
	return _c.mutation
}

// Save creates the OIDCAuthorizationCode in the database.
func (_c *OIDCAuthorizationCodeCreate) Save(ctx context.Context) (*OIDCAuthorizationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCAuthorizationCodeCreate) SaveX(ctx context.Context) *OIDCAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCAuthorizationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCAuthorizationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCAuthorizationCodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oidcauthorizationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCAuthorizationCodeCreate) check() error {
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.code_hash"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.client_id"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.redirect_uri"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.account_id"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.scope"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.nonce"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.code_challenge"`)}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.code_challenge_method"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OIDCAuthorizationCode.created_at"`)}
	}
	return nil
}

func (_c *OIDCAuthorizationCodeCreate) sqlSave(ctx context.Context) (*OIDCAuthorizationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCAuthorizationCodeCreate) createSpec() (*OIDCAuthorizationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCAuthorizationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcauthorizationcode.Table, sqlgraph.NewFieldSpec(oidcauthorizationcode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeHash, field.TypeBytes, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oidcauthorizationcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(oidcauthorizationcode.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(oidcauthorizationcode.FieldScope, field.TypeJSON, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(oidcauthorizationcode.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcauthorizationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OIDCAuthorizationCodeCreateBulk is the builder for creating many OIDCAuthorizationCode entities in bulk.
type OIDCAuthorizationCodeCreateBulk struct {
	config
	err      error
	builders []*OIDCAuthorizationCodeCreate
}

// Save creates the OIDCAuthorizationCode entities in the database.
func (_c *OIDCAuthorizationCodeCreateBulk) Save(ctx context.Context) ([]*OIDCAuthorizationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCAuthorizationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCAuthorizationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCAuthorizationCodeCreateBulk) SaveX(ctx context.Context) []*OIDCAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCAuthorizationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCAuthorizationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
