// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcaccesstoken"
	"github.com/sandbox-auth/src/ent/predicate"
)

// OIDCAccessTokenDelete is the builder for deleting a OIDCAccessToken entity.
type OIDCAccessTokenDelete struct {
	config
	hooks    []Hook
	mutation *OIDCAccessTokenMutation
}

// Where appends a list predicates to the OIDCAccessTokenDelete builder.
func (_d *OIDCAccessTokenDelete) Where(ps ...predicate.OIDCAccessToken) *OIDCAccessTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OIDCAccessTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCAccessTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OIDCAccessTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oidcaccesstoken.Table, sqlgraph.NewFieldSpec(oidcaccesstoken.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OIDCAccessTokenDeleteOne is the builder for deleting a single OIDCAccessToken entity.
type OIDCAccessTokenDeleteOne struct {
	_d *OIDCAccessTokenDelete
}

// Where appends a list predicates to the OIDCAccessTokenDelete builder.
func (_d *OIDCAccessTokenDeleteOne) Where(ps ...predicate.OIDCAccessToken) *OIDCAccessTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OIDCAccessTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oidcaccesstoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCAccessTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
