// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-auth/src/ent/oidcclient"
)

// OIDCClientCreate is the builder for creating a OIDCClient entity.
type OIDCClientCreate struct {
	config
	mutation *OIDCClientMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCClientCreate) SetCreatedAt(v time.Time) *OIDCClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCClientCreate) SetNillableCreatedAt(v *time.Time) *OIDCClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OIDCClientCreate) SetUpdatedAt(v time.Time) *OIDCClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OIDCClientCreate) SetNillableUpdatedAt(v *time.Time) *OIDCClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OIDCClientCreate) SetClientID(v string) *OIDCClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *OIDCClientCreate) SetClientSecretHash(v []byte) *OIDCClientCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *OIDCClientCreate) SetDisabled(v bool) *OIDCClientCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *OIDCClientCreate) SetNillableDisabled(v *bool) *OIDCClientCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// Mutation returns the OIDCClientMutation object of the builder.
func (_c *OIDCClientCreate) Mutation() *OIDCClientMutation {
	return _c.mutation
}

// Save creates the OIDCClient in the database.
func (_c *OIDCClientCreate) Save(ctx context.Context) (*OIDCClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCClientCreate) SaveX(ctx context.Context) *OIDCClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCClientCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oidcclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oidcclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := oidcclient.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCClientCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OIDCClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OIDCClient.updated_at"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OIDCClient.client_id"`)}
	}
	if _, ok := _c.mutation.ClientSecretHash(); !ok {
		return &ValidationError{Name: "client_secret_hash", err: errors.New(`ent: missing required field "OIDCClient.client_secret_hash"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "OIDCClient.disabled"`)}
	}
	return nil
}

func (_c *OIDCClientCreate) sqlSave(ctx context.Context) (*OIDCClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCClientCreate) createSpec() (*OIDCClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcclient.Table, sqlgraph.NewFieldSpec(oidcclient.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oidcclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(oidcclient.FieldClientSecretHash, field.TypeBytes, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(oidcclient.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	return _node, _spec
}

// OIDCClientCreateBulk is the builder for creating many OIDCClient entities in bulk.
type OIDCClientCreateBulk struct {
	config
	err      error
	builders []*OIDCClientCreate
}

// Save creates the OIDCClient entities in the database.
func (_c *OIDCClientCreateBulk) Save(ctx context.Context) ([]*OIDCClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCClientCreateBulk) SaveX(ctx context.Context) []*OIDCClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
