// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-auth/src/ent/oidcauthorizationcode"
)

// OIDCAuthorizationCode is the model entity for the OIDCAuthorizationCode schema.
type OIDCAuthorizationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash []byte `json:"code_hash,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// RedirectURI holds the value of the "redirect_uri" field.
	RedirectURI string `json:"redirect_uri,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope []string `json:"scope,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce string `json:"nonce,omitempty"`
	// CodeChallenge holds the value of the "code_challenge" field.
	CodeChallenge string `json:"code_challenge,omitempty"`
	// CodeChallengeMethod holds the value of the "code_challenge_method" field.
	CodeChallengeMethod string `json:"code_challenge_method,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCAuthorizationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidcauthorizationcode.FieldCodeHash, oidcauthorizationcode.FieldScope:
			values[i] = new([]byte)
		case oidcauthorizationcode.FieldID, oidcauthorizationcode.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case oidcauthorizationcode.FieldClientID, oidcauthorizationcode.FieldRedirectURI, oidcauthorizationcode.FieldNonce, oidcauthorizationcode.FieldCodeChallenge, oidcauthorizationcode.FieldCodeChallengeMethod:
			values[i] = new(sql.NullString)
		case oidcauthorizationcode.FieldExpiresAt, oidcauthorizationcode.FieldConsumedAt, oidcauthorizationcode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCAuthorizationCode fields.
func (_m *OIDCAuthorizationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidcauthorizationcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oidcauthorizationcode.FieldCodeHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value != nil {
				_m.CodeHash = *value
			}
		case oidcauthorizationcode.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oidcauthorizationcode.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				_m.RedirectURI = value.String
			}
		case oidcauthorizationcode.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case oidcauthorizationcode.FieldScope:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scope); err != nil {
					return fmt.Errorf("unmarshal field scope: %w", err)
				}
			}
		case oidcauthorizationcode.FieldNonce:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value.Valid {
				_m.Nonce = value.String
			}
		case oidcauthorizationcode.FieldCodeChallenge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_challenge", values[i])
			} else if value.Valid {
				_m.CodeChallenge = value.String
			}
		case oidcauthorizationcode.FieldCodeChallengeMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_challenge_method", values[i])
			} else if value.Valid {
				_m.CodeChallengeMethod = value.String
			}
		case oidcauthorizationcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oidcauthorizationcode.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case oidcauthorizationcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCAuthorizationCode.
// This includes values selected through modifiers, order, etc.
func (_m *OIDCAuthorizationCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OIDCAuthorizationCode.
// Note that you need to call OIDCAuthorizationCode.Unwrap() before calling this method if this OIDCAuthorizationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OIDCAuthorizationCode) Update() *OIDCAuthorizationCodeUpdateOne {
	return NewOIDCAuthorizationCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OIDCAuthorizationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OIDCAuthorizationCode) Unwrap() *OIDCAuthorizationCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCAuthorizationCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OIDCAuthorizationCode) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCAuthorizationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.CodeHash))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(_m.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(_m.Nonce)
	builder.WriteString(", ")
	builder.WriteString("code_challenge=")
	builder.WriteString(_m.CodeChallenge)
	builder.WriteString(", ")
	builder.WriteString("code_challenge_method=")
	builder.WriteString(_m.CodeChallengeMethod)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OIDCAuthorizationCodes is a parsable slice of OIDCAuthorizationCode.
type OIDCAuthorizationCodes []*OIDCAuthorizationCode
