// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/oidcaccesstoken"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// OIDCAccessTokenUpdate is the builder for updating OIDCAccessToken entities.
type OIDCAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OIDCAccessTokenMutation
}

// Where appends a list predicates to the OIDCAccessTokenUpdate builder.
func (_u *OIDCAccessTokenUpdate) Where(ps ...predicate.OIDCAccessToken) *OIDCAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OIDCAccessTokenUpdate) SetTokenHash(v []byte) *OIDCAccessTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCAccessTokenUpdate) SetClientID(v string) *OIDCAccessTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdate) SetNillableClientID(v *string) *OIDCAccessTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OIDCAccessTokenUpdate) SetAccountID(v int64) *OIDCAccessTokenUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdate) SetNillableAccountID(v *int64) *OIDCAccessTokenUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OIDCAccessTokenUpdate) AddAccountID(v int64) *OIDCAccessTokenUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *OIDCAccessTokenUpdate) SetScope(v []string) *OIDCAccessTokenUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// AppendScope appends value to the "scope" field.
func (_u *OIDCAccessTokenUpdate) AppendScope(v []string) *OIDCAccessTokenUpdate {
	_u.mutation.AppendScope(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OIDCAccessTokenUpdate) SetExpiresAt(v time.Time) *OIDCAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *OIDCAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OIDCAccessTokenUpdate) SetRevokedAt(v time.Time) *OIDCAccessTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdate) SetNillableRevokedAt(v *time.Time) *OIDCAccessTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OIDCAccessTokenUpdate) ClearRevokedAt() *OIDCAccessTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the OIDCAccessTokenMutation object of the builder.
func (_u *OIDCAccessTokenUpdate) Mutation() *OIDCAccessTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcaccesstoken.Table, oidcaccesstoken.Columns, sqlgraph.NewFieldSpec(oidcaccesstoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oidcaccesstoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcaccesstoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oidcaccesstoken.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(oidcaccesstoken.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oidcaccesstoken.FieldScope, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScope(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oidcaccesstoken.FieldScope, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oidcaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oidcaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCAccessTokenUpdateOne is the builder for updating a single OIDCAccessToken entity.
type OIDCAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OIDCAccessTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *OIDCAccessTokenUpdateOne) SetTokenHash(v []byte) *OIDCAccessTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OIDCAccessTokenUpdateOne) SetClientID(v string) *OIDCAccessTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdateOne) SetNillableClientID(v *string) *OIDCAccessTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OIDCAccessTokenUpdateOne) SetAccountID(v int64) *OIDCAccessTokenUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdateOne) SetNillableAccountID(v *int64) *OIDCAccessTokenUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OIDCAccessTokenUpdateOne) AddAccountID(v int64) *OIDCAccessTokenUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *OIDCAccessTokenUpdateOne) SetScope(v []string) *OIDCAccessTokenUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// AppendScope appends value to the "scope" field.
func (_u *OIDCAccessTokenUpdateOne) AppendScope(v []string) *OIDCAccessTokenUpdateOne {
	_u.mutation.AppendScope(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OIDCAccessTokenUpdateOne) SetExpiresAt(v time.Time) *OIDCAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OIDCAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OIDCAccessTokenUpdateOne) SetRevokedAt(v time.Time) *OIDCAccessTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OIDCAccessTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *OIDCAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OIDCAccessTokenUpdateOne) ClearRevokedAt() *OIDCAccessTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the OIDCAccessTokenMutation object of the builder.
func (_u *OIDCAccessTokenUpdateOne) Mutation() *OIDCAccessTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCAccessTokenUpdate builder.
func (_u *OIDCAccessTokenUpdateOne) Where(ps ...predicate.OIDCAccessToken) *OIDCAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCAccessTokenUpdateOne) Select(field string, fields ...string) *OIDCAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCAccessToken entity.
func (_u *OIDCAccessTokenUpdateOne) Save(ctx context.Context) (*OIDCAccessToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCAccessTokenUpdateOne) SaveX(ctx context.Context) *OIDCAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OIDCAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *OIDCAccessToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(oidcaccesstoken.Table, oidcaccesstoken.Columns, sqlgraph.NewFieldSpec(oidcaccesstoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcaccesstoken.FieldID)
		for _, f := range fields {
			if !oidcaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oidcaccesstoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oidcaccesstoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oidcaccesstoken.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(oidcaccesstoken.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oidcaccesstoken.FieldScope, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScope(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oidcaccesstoken.FieldScope, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oidcaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oidcaccesstoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oidcaccesstoken.FieldRevokedAt, field.TypeTime)
	}
	_node = &OIDCAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
