// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sandbox-nextjs/api/src/ent/account"
	"sandbox-nextjs/api/src/ent/schema"
	"sandbox-nextjs/api/src/ent/webauthncredential"
	"sandbox-nextjs/api/src/ent/webauthnsession"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescEmailVerified is the schema descriptor for email_verified field.
	accountDescEmailVerified := accountFields[3].Descriptor()
	// account.DefaultEmailVerified holds the default value on creation for the email_verified field.
	account.DefaultEmailVerified = accountDescEmailVerified.Default.(bool)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[4].Descriptor()
	// account.DefaultName holds the default value on creation for the name field.
	account.DefaultName = accountDescName.Default.(string)
	// accountDescPicture is the schema descriptor for picture field.
	accountDescPicture := accountFields[5].Descriptor()
	// account.DefaultPicture holds the default value on creation for the picture field.
	account.DefaultPicture = accountDescPicture.Default.(string)
	// accountDescDisplayName is the schema descriptor for display_name field.
	accountDescDisplayName := accountFields[6].Descriptor()
	// account.DefaultDisplayName holds the default value on creation for the display_name field.
	account.DefaultDisplayName = accountDescDisplayName.Default.(string)
	// accountDescBio is the schema descriptor for bio field.
	accountDescBio := accountFields[7].Descriptor()
	// account.DefaultBio holds the default value on creation for the bio field.
	account.DefaultBio = accountDescBio.Default.(string)
	webauthncredentialFields := schema.WebauthnCredential{}.Fields()
	_ = webauthncredentialFields
	// webauthncredentialDescCreatedAt is the schema descriptor for created_at field.
	webauthncredentialDescCreatedAt := webauthncredentialFields[3].Descriptor()
	// webauthncredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	webauthncredential.DefaultCreatedAt = webauthncredentialDescCreatedAt.Default.(func() time.Time)
	// webauthncredentialDescUpdatedAt is the schema descriptor for updated_at field.
	webauthncredentialDescUpdatedAt := webauthncredentialFields[4].Descriptor()
	// webauthncredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webauthncredential.DefaultUpdatedAt = webauthncredentialDescUpdatedAt.Default.(func() time.Time)
	// webauthncredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webauthncredential.UpdateDefaultUpdatedAt = webauthncredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	webauthnsessionFields := schema.WebauthnSession{}.Fields()
	_ = webauthnsessionFields
	// webauthnsessionDescCreatedAt is the schema descriptor for created_at field.
	webauthnsessionDescCreatedAt := webauthnsessionFields[5].Descriptor()
	// webauthnsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	webauthnsession.DefaultCreatedAt = webauthnsessionDescCreatedAt.Default.(func() time.Time)
}
