// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sandbox-auth/src/ent/account"
	"github.com/sandbox-auth/src/ent/authidentity"
	"github.com/sandbox-auth/src/ent/authsession"
	"github.com/sandbox-auth/src/ent/oidcaccesstoken"
	"github.com/sandbox-auth/src/ent/oidcauthorizationcode"
	"github.com/sandbox-auth/src/ent/oidcauthorizationtransaction"
	"github.com/sandbox-auth/src/ent/oidcclient"
	"github.com/sandbox-auth/src/ent/schema"
	"github.com/sandbox-auth/src/ent/webauthncredential"
	"github.com/sandbox-auth/src/ent/webauthnsession"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[0].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	authidentityMixin := schema.AuthIdentity{}.Mixin()
	authidentityMixinFields0 := authidentityMixin[0].Fields()
	_ = authidentityMixinFields0
	authidentityFields := schema.AuthIdentity{}.Fields()
	_ = authidentityFields
	// authidentityDescCreatedAt is the schema descriptor for created_at field.
	authidentityDescCreatedAt := authidentityMixinFields0[0].Descriptor()
	// authidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	authidentity.DefaultCreatedAt = authidentityDescCreatedAt.Default.(func() time.Time)
	// authidentityDescUpdatedAt is the schema descriptor for updated_at field.
	authidentityDescUpdatedAt := authidentityMixinFields0[1].Descriptor()
	// authidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authidentity.DefaultUpdatedAt = authidentityDescUpdatedAt.Default.(func() time.Time)
	// authidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authidentity.UpdateDefaultUpdatedAt = authidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authidentityDescEmailVerified is the schema descriptor for email_verified field.
	authidentityDescEmailVerified := authidentityFields[4].Descriptor()
	// authidentity.DefaultEmailVerified holds the default value on creation for the email_verified field.
	authidentity.DefaultEmailVerified = authidentityDescEmailVerified.Default.(bool)
	authsessionFields := schema.AuthSession{}.Fields()
	_ = authsessionFields
	// authsessionDescCreatedAt is the schema descriptor for created_at field.
	authsessionDescCreatedAt := authsessionFields[4].Descriptor()
	// authsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	authsession.DefaultCreatedAt = authsessionDescCreatedAt.Default.(func() time.Time)
	oidcaccesstokenFields := schema.OIDCAccessToken{}.Fields()
	_ = oidcaccesstokenFields
	// oidcaccesstokenDescCreatedAt is the schema descriptor for created_at field.
	oidcaccesstokenDescCreatedAt := oidcaccesstokenFields[6].Descriptor()
	// oidcaccesstoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oidcaccesstoken.DefaultCreatedAt = oidcaccesstokenDescCreatedAt.Default.(func() time.Time)
	oidcauthorizationcodeFields := schema.OIDCAuthorizationCode{}.Fields()
	_ = oidcauthorizationcodeFields
	// oidcauthorizationcodeDescCreatedAt is the schema descriptor for created_at field.
	oidcauthorizationcodeDescCreatedAt := oidcauthorizationcodeFields[10].Descriptor()
	// oidcauthorizationcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	oidcauthorizationcode.DefaultCreatedAt = oidcauthorizationcodeDescCreatedAt.Default.(func() time.Time)
	oidcauthorizationtransactionFields := schema.OIDCAuthorizationTransaction{}.Fields()
	_ = oidcauthorizationtransactionFields
	// oidcauthorizationtransactionDescState is the schema descriptor for state field.
	oidcauthorizationtransactionDescState := oidcauthorizationtransactionFields[4].Descriptor()
	// oidcauthorizationtransaction.DefaultState holds the default value on creation for the state field.
	oidcauthorizationtransaction.DefaultState = oidcauthorizationtransactionDescState.Default.(string)
	// oidcauthorizationtransactionDescCreatedAt is the schema descriptor for created_at field.
	oidcauthorizationtransactionDescCreatedAt := oidcauthorizationtransactionFields[10].Descriptor()
	// oidcauthorizationtransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	oidcauthorizationtransaction.DefaultCreatedAt = oidcauthorizationtransactionDescCreatedAt.Default.(func() time.Time)
	oidcclientMixin := schema.OIDCClient{}.Mixin()
	oidcclientMixinFields0 := oidcclientMixin[0].Fields()
	_ = oidcclientMixinFields0
	oidcclientFields := schema.OIDCClient{}.Fields()
	_ = oidcclientFields
	// oidcclientDescCreatedAt is the schema descriptor for created_at field.
	oidcclientDescCreatedAt := oidcclientMixinFields0[0].Descriptor()
	// oidcclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oidcclient.DefaultCreatedAt = oidcclientDescCreatedAt.Default.(func() time.Time)
	// oidcclientDescUpdatedAt is the schema descriptor for updated_at field.
	oidcclientDescUpdatedAt := oidcclientMixinFields0[1].Descriptor()
	// oidcclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oidcclient.DefaultUpdatedAt = oidcclientDescUpdatedAt.Default.(func() time.Time)
	// oidcclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oidcclient.UpdateDefaultUpdatedAt = oidcclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oidcclientDescDisabled is the schema descriptor for disabled field.
	oidcclientDescDisabled := oidcclientFields[2].Descriptor()
	// oidcclient.DefaultDisabled holds the default value on creation for the disabled field.
	oidcclient.DefaultDisabled = oidcclientDescDisabled.Default.(bool)
	webauthncredentialFields := schema.WebauthnCredential{}.Fields()
	_ = webauthncredentialFields
	// webauthncredentialDescCreatedAt is the schema descriptor for created_at field.
	webauthncredentialDescCreatedAt := webauthncredentialFields[3].Descriptor()
	// webauthncredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	webauthncredential.DefaultCreatedAt = webauthncredentialDescCreatedAt.Default.(func() time.Time)
	// webauthncredentialDescUpdatedAt is the schema descriptor for updated_at field.
	webauthncredentialDescUpdatedAt := webauthncredentialFields[4].Descriptor()
	// webauthncredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webauthncredential.DefaultUpdatedAt = webauthncredentialDescUpdatedAt.Default.(func() time.Time)
	// webauthncredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webauthncredential.UpdateDefaultUpdatedAt = webauthncredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	webauthnsessionFields := schema.WebauthnSession{}.Fields()
	_ = webauthnsessionFields
	// webauthnsessionDescCreatedAt is the schema descriptor for created_at field.
	webauthnsessionDescCreatedAt := webauthnsessionFields[5].Descriptor()
	// webauthnsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	webauthnsession.DefaultCreatedAt = webauthnsessionDescCreatedAt.Default.(func() time.Time)
}
