// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sandbox-nextjs/api/src/ent/webauthnsession"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WebauthnSession is the model entity for the WebauthnSession schema.
type WebauthnSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Ceremony holds the value of the "ceremony" field.
	Ceremony string `json:"ceremony,omitempty"`
	// SessionJSON holds the value of the "session_json" field.
	SessionJSON json.RawMessage `json:"session_json,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebauthnSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webauthnsession.FieldSessionJSON:
			values[i] = new([]byte)
		case webauthnsession.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case webauthnsession.FieldID, webauthnsession.FieldCeremony:
			values[i] = new(sql.NullString)
		case webauthnsession.FieldExpiresAt, webauthnsession.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebauthnSession fields.
func (_m *WebauthnSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webauthnsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case webauthnsession.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case webauthnsession.FieldCeremony:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ceremony", values[i])
			} else if value.Valid {
				_m.Ceremony = value.String
			}
		case webauthnsession.FieldSessionJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SessionJSON); err != nil {
					return fmt.Errorf("unmarshal field session_json: %w", err)
				}
			}
		case webauthnsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case webauthnsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebauthnSession.
// This includes values selected through modifiers, order, etc.
func (_m *WebauthnSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebauthnSession.
// Note that you need to call WebauthnSession.Unwrap() before calling this method if this WebauthnSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebauthnSession) Update() *WebauthnSessionUpdateOne {
	return NewWebauthnSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebauthnSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebauthnSession) Unwrap() *WebauthnSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebauthnSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebauthnSession) String() string {
	var builder strings.Builder
	builder.WriteString("WebauthnSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("ceremony=")
	builder.WriteString(_m.Ceremony)
	builder.WriteString(", ")
	builder.WriteString("session_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionJSON))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebauthnSessions is a parsable slice of WebauthnSession.
type WebauthnSessions []*WebauthnSession
