// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-auth/src/ent/webauthncredential"
)

// WebauthnCredential is the model entity for the WebauthnCredential schema.
type WebauthnCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// CredentialID holds the value of the "credential_id" field.
	CredentialID []byte `json:"credential_id,omitempty"`
	// CredentialJSON holds the value of the "credential_json" field.
	CredentialJSON json.RawMessage `json:"credential_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt   *time.Time `json:"last_used_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebauthnCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webauthncredential.FieldCredentialID, webauthncredential.FieldCredentialJSON:
			values[i] = new([]byte)
		case webauthncredential.FieldID, webauthncredential.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case webauthncredential.FieldCreatedAt, webauthncredential.FieldUpdatedAt, webauthncredential.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebauthnCredential fields.
func (_m *WebauthnCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webauthncredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case webauthncredential.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case webauthncredential.FieldCredentialID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value != nil {
				_m.CredentialID = *value
			}
		case webauthncredential.FieldCredentialJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CredentialJSON); err != nil {
					return fmt.Errorf("unmarshal field credential_json: %w", err)
				}
			}
		case webauthncredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case webauthncredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case webauthncredential.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebauthnCredential.
// This includes values selected through modifiers, order, etc.
func (_m *WebauthnCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebauthnCredential.
// Note that you need to call WebauthnCredential.Unwrap() before calling this method if this WebauthnCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebauthnCredential) Update() *WebauthnCredentialUpdateOne {
	return NewWebauthnCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebauthnCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebauthnCredential) Unwrap() *WebauthnCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebauthnCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebauthnCredential) String() string {
	var builder strings.Builder
	builder.WriteString("WebauthnCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("credential_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialID))
	builder.WriteString(", ")
	builder.WriteString("credential_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialJSON))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WebauthnCredentials is a parsable slice of WebauthnCredential.
type WebauthnCredentials []*WebauthnCredential
