// Code generated by ent, DO NOT EDIT.

package oidcauthorizationtransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldID, id))
}

// TransactionHash applies equality check predicate on the "transaction_hash" field. It's identical to TransactionHashEQ.
func TransactionHash(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldTransactionHash, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldClientID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldRedirectURI, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldState, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldNonce, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeMethod applies equality check predicate on the "code_challenge_method" field. It's identical to CodeChallengeMethodEQ.
func CodeChallengeMethod(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// TransactionHashEQ applies the EQ predicate on the "transaction_hash" field.
func TransactionHashEQ(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldTransactionHash, v))
}

// TransactionHashNEQ applies the NEQ predicate on the "transaction_hash" field.
func TransactionHashNEQ(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldTransactionHash, v))
}

// TransactionHashIn applies the In predicate on the "transaction_hash" field.
func TransactionHashIn(vs ...[]byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldTransactionHash, vs...))
}

// TransactionHashNotIn applies the NotIn predicate on the "transaction_hash" field.
func TransactionHashNotIn(vs ...[]byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldTransactionHash, vs...))
}

// TransactionHashGT applies the GT predicate on the "transaction_hash" field.
func TransactionHashGT(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldTransactionHash, v))
}

// TransactionHashGTE applies the GTE predicate on the "transaction_hash" field.
func TransactionHashGTE(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldTransactionHash, v))
}

// TransactionHashLT applies the LT predicate on the "transaction_hash" field.
func TransactionHashLT(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldTransactionHash, v))
}

// TransactionHashLTE applies the LTE predicate on the "transaction_hash" field.
func TransactionHashLTE(v []byte) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldTransactionHash, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldClientID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldRedirectURI, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldState, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldNonce, v))
}

// NonceContains applies the Contains predicate on the "nonce" field.
func NonceContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldNonce, v))
}

// NonceHasPrefix applies the HasPrefix predicate on the "nonce" field.
func NonceHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldNonce, v))
}

// NonceHasSuffix applies the HasSuffix predicate on the "nonce" field.
func NonceHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldNonce, v))
}

// NonceEqualFold applies the EqualFold predicate on the "nonce" field.
func NonceEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldNonce, v))
}

// NonceContainsFold applies the ContainsFold predicate on the "nonce" field.
func NonceContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldNonce, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// CodeChallengeMethodEQ applies the EQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodNEQ applies the NEQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodNEQ(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIn applies the In predicate on the "code_challenge_method" field.
func CodeChallengeMethodIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodNotIn applies the NotIn predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotIn(vs ...string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodGT applies the GT predicate on the "code_challenge_method" field.
func CodeChallengeMethodGT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodGTE applies the GTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodGTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLT applies the LT predicate on the "code_challenge_method" field.
func CodeChallengeMethodLT(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLTE applies the LTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodLTE(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContains applies the Contains predicate on the "code_challenge_method" field.
func CodeChallengeMethodContains(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContains(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasPrefix applies the HasPrefix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasPrefix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasPrefix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasSuffix applies the HasSuffix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasSuffix(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldHasSuffix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodEqualFold applies the EqualFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodEqualFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEqualFold(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContainsFold applies the ContainsFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodContainsFold(v string) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldContainsFold(FieldCodeChallengeMethod, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotNull(FieldConsumedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCAuthorizationTransaction) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCAuthorizationTransaction) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCAuthorizationTransaction) predicate.OIDCAuthorizationTransaction {
	return predicate.OIDCAuthorizationTransaction(sql.NotPredicates(p))
}
