apiVersion: v1
kind: ConfigMap
metadata:
  name: sandbox-auth-api-config
data:
  ADDR: ":8080"
  FRONTEND_URL: "https://auth.example.com"
  DEFAULT_REDIRECT_URL: "https://auth.example.com/mypage"
  ALLOWED_REDIRECT_URLS: "https://auth.example.com/mypage"
  CORS_ALLOWED_ORIGINS: "https://auth.example.com"
  DB_HOST: "sandbox-auth-database.sandbox-auth.svc.cluster.local"
  DB_NAME: "test"
  DB_PORT: "5432"
  DB_SSLMODE: "disable"
  GOOGLE_REDIRECT_URL: "https://auth.example.com/api/auth/google/callback"
  PASSKEY_RP_ID: "auth.example.com"
  PASSKEY_RP_ORIGIN: "https://auth.example.com"
  TRUSTED_PROXIES: ""
